apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moonihun/gitops.git
    targetRevision: main
    path: infra/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

