apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.18
      helm: 
        valueFiles: 
          - $values/infra/nfs-subdir-external-provisioner/values.yaml
    - repoURL: https://github.com/moonihun/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
