apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://emberstack.github.io/helm-charts
      chart: reflector
      targetRevision: 10.0.17
      helm:
        valueFiles:
          - $values/infra/reflector/values.yaml 
    - repoURL: https://github.com/moonihun/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

