apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: vault-app
  namespace: argocd 
spec:
  project: default 
  sources:
    - repoURL: https://helm.releases.hashicorp.com 
      chart: vault 
      targetRevision: "0.32.0"
      helm:
        valueFiles:
          - $values/infra/values/vault-values.yaml
    - repoURL: https://github.com/moonihun/gitops.git 
      targetRevision: main 
      ref: values
  destination:
    server: https://kubernetes.default.svc 
    namespace: vault 
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
