apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h 
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore 
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner 
  data:
    - secretKey: api-token
      remoteeRef:
        key: secret/prod/cert-manager 
        property: cf-api-token
