global:
  image: docker.io/hashicorp/vault 
server:
  dev:
    enabled: false 
  ha:
    enabled: false
  dataStorage:
    enabled: true 
    size: 5Gi
    storageClass: nfs 
  ui:
    enabled: true 
  ingress:
    enabled: false 

injector:
  enabled: false
